modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/Captcha/issues"
license="MIT"

[[mods]]
modId="captcha"
version="${file.jarVersion}"
displayName="Captcha"
displayURL="https://www.curseforge.com/minecraft/mc-mods/captcha"
authors="Mrbysco, ShyNieke, JackRuby1"
logoFile="icon.png"
description='''
Ever thought it'd be a great idea to require a Captcha to open an inventory? Well, this is the mod you are looking for!
'''
[[dependencies.captcha]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"