modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/Mrbysco/Captcha/issues"
license="MIT"

[[mods]]
modId="captcha"
version="${file.jarVersion}"
displayName="Captcha"
displayURL="https://www.curseforge.com/minecraft/mc-mods/captcha"
authors="Mrbysco, JackRuby1"
description='''
Ever thought it'd be a great idea to require a Captcha to open an inventory? Well, this is the mod you are looking for!
'''
[[dependencies.captcha]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.captcha]]
modId="forge"
mandatory=true
versionRange="[45.1.0,)"
ordering="NONE"
side="BOTH"